- name: installig few  softwares and removing few softwares
  hosts: local
  become: yes
  connection: local
  tasks:
  - name: installing packages and removing packages
    ansible.builtin.package:
      name: "{{ item.name }}"
      state: "{{ item.state }}"
    loop:
    - {name: 'nginx' , state: 'absent'}
    - {name: 'mysql', state: 'absent'}
    