- name: loop in ansible
  hosts: local
  connections: local
  tasks:
  - name: printing the loops in ansible 
    ansible.builtin.debug:
      msg: "printing the values inside the loops {{ item }}"
    loop:
    - suresh
    - ramesh
    - monnish