- name: play level variables
  hosts: local
  connection: local
  become: yes
  vars:
    name: "monnish"
    course: "ansible"
  tasks:
  
  - name: printing the course information
    vars:
      course: "latest ansible"
    ansible.builtin.debug:
      msg: "the course name is {{ course }} and the trainer is {{ name }}"

  - name: printing the  second course information
    vars:
      course: "latest ansible"
    ansible.builtin.debug:
      msg: "the course name is {{ course }} and the trainer is {{ name }}"