- name: promt variables in ansible
  hosts: local
  connections: local
  vars_prompt:
  - name: username
    prompt: please enter your name
    private: true
  - name: pass
    prompt: please enter password
    private: false
  tasks:
   - name: testting the tasks level variables
     ansible.builtin.debug:
      msg: "hi {{ username}} and your password is {{ pass }}"
    