- name: task level variables
  hosts: local
  connection: local
  vars:
    course: ansible
    trainer: monnish
  tasks:
  - name: printing the couse information
    vars:
        course: ansible tasks
    ansible.builtin.debug:
      msg: " the course name is {{ course }} ans trainer is {{ trainer }}"