- name: play level variables
  hosts: local
  connection: local
  become: yes
  #play level variables
  vars:
    name: "monnish"
    course: "ansible"
  vars_files:
  - course.yaml
  tasks:
  
  - name: printing the course information
  #task level variables
    vars:
      course: "latest ansible"
    ansible.builtin.debug:
      msg: "the course name is {{ course }} and the trainer is {{ name }}"

  - name: printing the  second course information
    ansible.builtin.debug:
      msg: "the course name is {{ course }} and the trainer is {{ name }}"